name: example-environment
channels:
  - conda-forge
  - default
dependencies:
  - python=3.9
  - r=4.0
  - plotly
  - pandas
  - matplotlib
  - scikit-learn
  - numpy
  - seaborn
  - statsmodels
  - r-dplyr
  - r-ggplot2
  - r-reshape2
  - r-tidyverse
  - r-stringr
